language: csharp
mono: none
dotnet: 3.0.100
dist: trusty
sudo: required
script:
  - sudo apt-get update 
  - sudo apt-get install -y libgdiplus
  - cd ZKWeb/ZKWeb.Console
  - dotnet restore
  - dotnet run -c Release -f netcoreapp3.0
