language: csharp
mono: none
dotnet: 2.2.100
dist: trusty
sudo: required
before_install:
  - sudo apt-get update 
  - sudo apt-get install -y dpkg # fix control.tar.xz issue
script:
  - sudo apt-get install libgdiplus -y
  - sudo ln -s /usr/lib/libgdiplus.so /usr/lib/gdiplus.dll
  - cd ZKWeb/ZKWeb.Console
  - dotnet restore
  - dotnet run -c Release -f netcoreapp2.2
