language: csharp
mono: none
dotnet: 2.0.2
dist: trusty
sudo: required
script:
  - sudo apt-get install libgdiplus -y
  - sudo ln -s /usr/lib/libgdiplus.so /usr/lib/gdiplus.dll
  - cd ZKWeb/ZKWeb.Console
  - dotnet restore
  - dotnet run -c Release -f netcoreapp2.0
